/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRoadmapRouteImport } from './routes/_app.roadmap'
import { Route as AppRiskRouteImport } from './routes/_app.risk'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppRecommendationsRouteImport } from './routes/_app.recommendations'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppLeadEngineRouteImport } from './routes/_app.lead-engine'
import { Route as AppHealthRouteImport } from './routes/_app.health'
import { Route as AppExecutiveSummaryRouteImport } from './routes/_app.executive-summary'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCompetitorsRouteImport } from './routes/_app.competitors'
import { Route as AppBoardroomRouteImport } from './routes/_app.boardroom'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppActivityRouteImport } from './routes/_app.activity'
import { Route as AppAgentsAgentIdRouteImport } from './routes/_app.agents.$agentId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRoadmapRoute = AppRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AppRoute,
} as any)
const AppRiskRoute = AppRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRecommendationsRoute = AppRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadEngineRoute = AppLeadEngineRouteImport.update({
  id: '/lead-engine',
  path: '/lead-engine',
  getParentRoute: () => AppRoute,
} as any)
const AppHealthRoute = AppHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AppRoute,
} as any)
const AppExecutiveSummaryRoute = AppExecutiveSummaryRouteImport.update({
  id: '/executive-summary',
  path: '/executive-summary',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCompetitorsRoute = AppCompetitorsRouteImport.update({
  id: '/competitors',
  path: '/competitors',
  getParentRoute: () => AppRoute,
} as any)
const AppBoardroomRoute = AppBoardroomRouteImport.update({
  id: '/boardroom',
  path: '/boardroom',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsAgentIdRoute = AppAgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/activity': typeof AppActivityRoute
  '/analytics': typeof AppAnalyticsRoute
  '/boardroom': typeof AppBoardroomRoute
  '/competitors': typeof AppCompetitorsRoute
  '/dashboard': typeof AppDashboardRoute
  '/executive-summary': typeof AppExecutiveSummaryRoute
  '/health': typeof AppHealthRoute
  '/lead-engine': typeof AppLeadEngineRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/recommendations': typeof AppRecommendationsRoute
  '/reports': typeof AppReportsRoute
  '/risk': typeof AppRiskRoute
  '/roadmap': typeof AppRoadmapRoute
  '/settings': typeof AppSettingsRoute
  '/agents/$agentId': typeof AppAgentsAgentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/activity': typeof AppActivityRoute
  '/analytics': typeof AppAnalyticsRoute
  '/boardroom': typeof AppBoardroomRoute
  '/competitors': typeof AppCompetitorsRoute
  '/dashboard': typeof AppDashboardRoute
  '/executive-summary': typeof AppExecutiveSummaryRoute
  '/health': typeof AppHealthRoute
  '/lead-engine': typeof AppLeadEngineRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/recommendations': typeof AppRecommendationsRoute
  '/reports': typeof AppReportsRoute
  '/risk': typeof AppRiskRoute
  '/roadmap': typeof AppRoadmapRoute
  '/settings': typeof AppSettingsRoute
  '/agents/$agentId': typeof AppAgentsAgentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/boardroom': typeof AppBoardroomRoute
  '/_app/competitors': typeof AppCompetitorsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/executive-summary': typeof AppExecutiveSummaryRoute
  '/_app/health': typeof AppHealthRoute
  '/_app/lead-engine': typeof AppLeadEngineRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/recommendations': typeof AppRecommendationsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/risk': typeof AppRiskRoute
  '/_app/roadmap': typeof AppRoadmapRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/agents/$agentId': typeof AppAgentsAgentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/activity'
    | '/analytics'
    | '/boardroom'
    | '/competitors'
    | '/dashboard'
    | '/executive-summary'
    | '/health'
    | '/lead-engine'
    | '/notifications'
    | '/profile'
    | '/recommendations'
    | '/reports'
    | '/risk'
    | '/roadmap'
    | '/settings'
    | '/agents/$agentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/activity'
    | '/analytics'
    | '/boardroom'
    | '/competitors'
    | '/dashboard'
    | '/executive-summary'
    | '/health'
    | '/lead-engine'
    | '/notifications'
    | '/profile'
    | '/recommendations'
    | '/reports'
    | '/risk'
    | '/roadmap'
    | '/settings'
    | '/agents/$agentId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/_app/activity'
    | '/_app/analytics'
    | '/_app/boardroom'
    | '/_app/competitors'
    | '/_app/dashboard'
    | '/_app/executive-summary'
    | '/_app/health'
    | '/_app/lead-engine'
    | '/_app/notifications'
    | '/_app/profile'
    | '/_app/recommendations'
    | '/_app/reports'
    | '/_app/risk'
    | '/_app/roadmap'
    | '/_app/settings'
    | '/_app/agents/$agentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roadmap': {
      id: '/_app/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AppRoadmapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/risk': {
      id: '/_app/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof AppRiskRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recommendations': {
      id: '/_app/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof AppRecommendationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lead-engine': {
      id: '/_app/lead-engine'
      path: '/lead-engine'
      fullPath: '/lead-engine'
      preLoaderRoute: typeof AppLeadEngineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/health': {
      id: '/_app/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AppHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/executive-summary': {
      id: '/_app/executive-summary'
      path: '/executive-summary'
      fullPath: '/executive-summary'
      preLoaderRoute: typeof AppExecutiveSummaryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/competitors': {
      id: '/_app/competitors'
      path: '/competitors'
      fullPath: '/competitors'
      preLoaderRoute: typeof AppCompetitorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/boardroom': {
      id: '/_app/boardroom'
      path: '/boardroom'
      fullPath: '/boardroom'
      preLoaderRoute: typeof AppBoardroomRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/$agentId': {
      id: '/_app/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AppAgentsAgentIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBoardroomRoute: typeof AppBoardroomRoute
  AppCompetitorsRoute: typeof AppCompetitorsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppExecutiveSummaryRoute: typeof AppExecutiveSummaryRoute
  AppHealthRoute: typeof AppHealthRoute
  AppLeadEngineRoute: typeof AppLeadEngineRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRecommendationsRoute: typeof AppRecommendationsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRiskRoute: typeof AppRiskRoute
  AppRoadmapRoute: typeof AppRoadmapRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppAgentsAgentIdRoute: typeof AppAgentsAgentIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBoardroomRoute: AppBoardroomRoute,
  AppCompetitorsRoute: AppCompetitorsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppExecutiveSummaryRoute: AppExecutiveSummaryRoute,
  AppHealthRoute: AppHealthRoute,
  AppLeadEngineRoute: AppLeadEngineRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppRecommendationsRoute: AppRecommendationsRoute,
  AppReportsRoute: AppReportsRoute,
  AppRiskRoute: AppRiskRoute,
  AppRoadmapRoute: AppRoadmapRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppAgentsAgentIdRoute: AppAgentsAgentIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
